import type { MatchRecord, StoredPlayer } from "@/types/match";

// Statistics and "things to improve" computed in code from the user's own saved matches.
// Nothing here is generated by an AI model and nothing is fabricated: with too few matches we say so.

export const MIN_GAMES_FOR_INSIGHTS = 3;
const WINDOW = 20; // insights look at the latest 20 matches

export interface Summary {
  games: number;
  wins: number;
  winRate: number; // 0-1
  avgKills: number;
  avgDeaths: number;
  avgAssists: number;
  kda: number;
  avgGold: number;
  avgRating: number;
  mvpCount: number;
}

const mean = (xs: number[]) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0);
export const kdaOf = (k: number, d: number, a: number) => (k + a) / Math.max(d, 1);

export function summarize(ms: MatchRecord[]): Summary | null {
  if (ms.length === 0) return null;
  const wins = ms.filter((m) => m.result === "victory").length;
  const k = mean(ms.map((m) => m.kills));
  const d = mean(ms.map((m) => m.deaths));
  const a = mean(ms.map((m) => m.assists));
  return {
    games: ms.length,
    wins,
    winRate: wins / ms.length,
    avgKills: k,
    avgDeaths: d,
    avgAssists: a,
    kda: kdaOf(k, d, a),
    avgGold: mean(ms.map((m) => m.gold)),
    avgRating: mean(ms.map((m) => m.rating)),
    mvpCount: ms.filter((m) => m.mvp).length,
  };
}

export interface HeroLine {
  heroId: string | null;
  heroName: string;
  games: number;
  wins: number;
  winRate: number;
  kda: number;
}

export function byHero(ms: MatchRecord[]): HeroLine[] {
  const groups = new Map<string, MatchRecord[]>();
  for (const m of ms) {
    const key = m.myHeroId ?? `name:${m.myHeroName.toLowerCase()}`;
    groups.set(key, [...(groups.get(key) ?? []), m]);
  }
  return [...groups.values()]
    .map((g) => {
      const wins = g.filter((m) => m.result === "victory").length;
      return {
        heroId: g[0].myHeroId,
        heroName: g[0].myHeroName,
        games: g.length,
        wins,
        winRate: wins / g.length,
        kda: kdaOf(mean(g.map((m) => m.kills)), mean(g.map((m) => m.deaths)), mean(g.map((m) => m.assists))),
      };
    })
    .sort((a, b) => b.games - a.games || b.winRate - a.winRate);
}

export interface Insight {
  id: string;
  tone: "good" | "warn";
  title: string;
  detail: string;
}

const mates = (m: MatchRecord): StoredPlayer[] => m.players.filter((p) => p.team === m.myTeam && !p.isMe);

export function buildInsights(all: MatchRecord[]): Insight[] {
  if (all.length < MIN_GAMES_FOR_INSIGHTS) return [];
  const ms = all.slice(0, WINDOW).filter((m) => mates(m).length > 0);
  if (ms.length < MIN_GAMES_FOR_INSIGHTS) return [];
  const n = ms.length;
  const out: Insight[] = [];

  // 1) Deaths vs teammates
  const myDeaths = mean(ms.map((m) => m.deaths));
  const mateDeaths = mean(ms.map((m) => mean(mates(m).map((p) => p.deaths))));
  if (myDeaths - mateDeaths >= 1 && myDeaths >= mateDeaths * 1.25) {
    out.push({
      id: "deaths-high",
      tone: "warn",
      title: "ตายมากกว่าเพื่อนร่วมทีม",
      detail: `เฉลี่ย ${myDeaths.toFixed(1)} ครั้ง/เกม เทียบกับเพื่อนร่วมทีม ${mateDeaths.toFixed(1)} ครั้ง (${n} แมตช์ล่าสุด) ลองถอยตั้งหลักเร็วขึ้นเมื่อเสียเปรียบ`,
    });
  } else if (mateDeaths - myDeaths >= 1 && myDeaths <= mateDeaths * 0.75) {
    out.push({
      id: "deaths-low",
      tone: "good",
      title: "ตายน้อยกว่าเพื่อนร่วมทีม",
      detail: `เฉลี่ย ${myDeaths.toFixed(1)} ครั้ง/เกม เทียบกับเพื่อนร่วมทีม ${mateDeaths.toFixed(1)} ครั้ง (${n} แมตช์ล่าสุด)`,
    });
  }

  // 2) Gold vs teammates (role matters: roaming usually earns less gold)
  const myGold = mean(ms.map((m) => m.gold));
  const mateGold = mean(ms.map((m) => mean(mates(m).map((p) => p.gold))));
  if (mateGold > 0) {
    const ratio = myGold / mateGold;
    if (ratio < 0.9) {
      out.push({
        id: "gold-low",
        tone: "warn",
        title: "ทองต่ำกว่าเพื่อนร่วมทีม",
        detail: `ได้ทองเฉลี่ย ${Math.round(ratio * 100)}% ของเพื่อนร่วมทีม (${n} แมตช์ล่าสุด) ทั้งนี้ขึ้นกับบทบาท เช่น Roaming มักได้ทองน้อยกว่าอยู่แล้ว`,
      });
    } else if (ratio >= 1.1) {
      out.push({
        id: "gold-high",
        tone: "good",
        title: "ฟาร์มทองได้ดีกว่าเพื่อนร่วมทีม",
        detail: `ได้ทองเฉลี่ย ${Math.round(ratio * 100)}% ของเพื่อนร่วมทีม (${n} แมตช์ล่าสุด)`,
      });
    }
  }

  // 3) Kill participation = (kills + assists) / team kills
  const kps = ms
    .map((m) => ({ tk: m.myTeam === "blue" ? m.scoreBlue : m.scoreRed, ka: m.kills + m.assists }))
    .filter((x) => x.tk > 0)
    .map((x) => Math.min(x.ka / x.tk, 1));
  if (kps.length >= MIN_GAMES_FOR_INSIGHTS) {
    const kp = mean(kps);
    if (kp < 0.45) {
      out.push({
        id: "kp-low",
        tone: "warn",
        title: "เข้าร่วมการสู้น้อย",
        detail: `มีส่วนร่วมใน ${Math.round(kp * 100)}% ของ Kill ทีม (${kps.length} แมตช์) ลองเข้าร่วมการสู้ของทีมให้บ่อยขึ้น`,
      });
    } else if (kp >= 0.65) {
      out.push({
        id: "kp-high",
        tone: "good",
        title: "เข้าร่วมการสู้สม่ำเสมอ",
        detail: `มีส่วนร่วมใน ${Math.round(kp * 100)}% ของ Kill ทีม (${kps.length} แมตช์)`,
      });
    }
  }

  // 4) Rating vs teammates
  const myRating = mean(ms.map((m) => m.rating));
  const mateRating = mean(ms.map((m) => mean(mates(m).map((p) => p.rating))));
  if (myRating - mateRating <= -1) {
    out.push({
      id: "rating-low",
      tone: "warn",
      title: "คะแนนเฉลี่ยต่ำกว่าเพื่อนร่วมทีม",
      detail: `${myRating.toFixed(1)} เทียบกับเพื่อนร่วมทีม ${mateRating.toFixed(1)} (${n} แมตช์ล่าสุด)`,
    });
  } else if (myRating - mateRating >= 1) {
    out.push({
      id: "rating-high",
      tone: "good",
      title: "คะแนนเฉลี่ยสูงกว่าเพื่อนร่วมทีม",
      detail: `${myRating.toFixed(1)} เทียบกับเพื่อนร่วมทีม ${mateRating.toFixed(1)} (${n} แมตช์ล่าสุด)`,
    });
  }

  // 5) Hero win rate (needs 3+ games on that hero)
  const heroes = byHero(ms).filter((h) => h.games >= MIN_GAMES_FOR_INSIGHTS);
  const worst = [...heroes].sort((a, b) => a.winRate - b.winRate)[0];
  const best = [...heroes].sort((a, b) => b.winRate - a.winRate)[0];
  if (worst && worst.winRate <= 0.35) {
    out.push({
      id: "hero-worst",
      tone: "warn",
      title: `${worst.heroName} ชนะน้อย`,
      detail: `ชนะ ${worst.wins} จาก ${worst.games} เกม ลองทบทวนการเล่นหรือเลือกตัวที่ถนัดกว่า`,
    });
  }
  if (best && best.winRate >= 0.65 && best !== worst) {
    out.push({
      id: "hero-best",
      tone: "good",
      title: `${best.heroName} คือตัวที่ชนะบ่อย`,
      detail: `ชนะ ${best.wins} จาก ${best.games} เกม`,
    });
  }

  return [...out.filter((i) => i.tone === "warn"), ...out.filter((i) => i.tone === "good")].slice(0, 4);
}
